### ISSUE TITLE
Not able to write content into excel in windows

### ISSUE THREAD

**Issue by Sujay-shetty** [extrabacon/pyspreadsheet#14]
Hi,

The 'pyspreadsheet' module installed successfully in windows machine with all dependencies. But when I try to write content into excel sheet I'm getting following error.

Error: This socket is closed.
    at Socket._write (net.js:635:19)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at PythonShell.send (E:\Projects\node_modules\pyspreadsheet\node_modules\python-shell\index.js:156:20)
    at new SpreadsheetWriter (E:\Projects\node_modules\pyspreadsheet\lib\spreadsheet-writer.js:88:18)
    at new prepareHeaders (E:\Projects\DCE_CDRRepo\cdr\Coordination\CoordinationCombinationExport\jscripts\pre
pareHeaders.js:9:17)
    at E:\Projects\DCE_CDRRepo\cdr\Coordination\CoordinationCombinationExport\app.js:180:32
    at fn (E:\Projects\node_modules\async\lib\async.js:579:34).

I tried most of the alternative available in google to fix this issue but I could not resolve the issue.

Please help me to resolve the issue as soon as possible.

Thanks in Advance,
Sujay

**Comment by extrabacon** [comment]
It looks like you are writing after the process has ended (stdin is closed). Can you share some sample code?

**Comment by Sujay-shetty** [comment]
I created a common method for this to be used by different modules and following is the way in which I'm using the method.

prepareHeadersClass.start(pivotCMRHeaderParentArray,pivotCharParentArray,pivotValueParentArray,callback);

var SpreadsheetWriter = require('pyspreadsheet').SpreadsheetWriter;
var path = require('path');
var fs = require('fs');

function prepareHeaders(mysqlMod,config)
{
  this.current_path_to_locales_dir = path.join(__dirname, "../../");
  //fs.unlinkSync(this.current_path_to_locales_dir+config.config.filePath);
  this.writer = new SpreadsheetWriter(this.current_path_to_locales_dir+config.config.filePath);

  var objectheaderFormatClass = require("./headerFormat.js");
  this.objectheaderFormatFunction = new objectheaderFormatClass(this.writer);  
}

prepareHeaders.prototype.start = function(pivotCMRHeaderParentArray,pivotCharParentArray,pivotValueParentArray,parentCallback) 
{ 
  this.objectheaderFormatFunction.format();    
  this.objectheaderFormatFunction.prepareFirstHeader(pivotCMRHeaderParentArray);
  this.objectheaderFormatFunction.prepareSecondHeader(pivotCharParentArray);   
  this.objectheaderFormatFunction.create(pivotValueParentArray,parentCallback);  
}

module.exports = prepareHeaders;

Note : The above code is working fine in linux machine but it is not working in Windows machine.

**Comment by extrabacon** [comment]
The problem is likely when you render the file, which I cannot see from your code sample. Writes are still being performed after the underlying process has been closed. Pay extra attention to how you make your asynchronous calls.

**Comment by Sujay-shetty** [comment]
The above code is the entry point where after creating the header the content are written. But In Windows machine it is breaking at this point only.

In Linux machine code is working perfectly fine.

Please give some suggestion to solve this issue.

**Comment by extrabacon** [comment]
I suspect the Python script is failing on Windows, causing the process to shutdown prematurely. In this case I would recommend a pure JS library instead of Python interop.

Take a look at http://sheetjs.com/
